For the Random Stock PR
endless-sky/endless-sky-wiki pull request #24
Opened 2024-06-24 10:49 UTC by TheGiraffe3

**New feature**

[#10265](https://github.com/endless-sky/endless-sky/pull/10265)

## Summary

This PR adds the information for [#10265](https://github.com/endless-sky/endless-sky/pull/10265) at the main repository.

2024-06-24 11:51 UTC, TheGiraffe3 commented
@Zarkonnen I’m not sure how to document the event adding and removing shipyards/outfitters. Can you help with that/add that?

2024-06-24 11:55 UTC, Zarkonnen commented
> @Zarkonnen I’m not sure how to document the event adding and removing shipyards/outfitters. Can you help with that/add that?

Will do so later today. :)

2024-06-25 07:37 UTC, Zarkonnen commented
FFS I have no idea how to use any of this github stuff. How do I add suggested changes?

2024-06-25 08:00 UTC, TheGiraffe3 commented
I'll change it. But you click to the left side of the file on the number.

2024-06-25 18:37 UTC, mOctave commented
> FFS I have no idea how to use any of this github stuff. How do I add suggested changes?

Go to "files changed"
<img width="671" alt="Screenshot 2024-06-25 at 11 32 14 AM" src="https://github.com/endless-sky/endless-sky-wiki/assets/73318970/5dd1b9dc-85f7-43bf-b852-b15f33736469">
Find the line you want to suggest changes on, and hit the plus button
<img width="710" alt="Screenshot 2024-06-25 at 11 32 34 AM" src="https://github.com/endless-sky/endless-sky-wiki/assets/73318970/081965fb-0a4e-442b-86fd-b302bfee5b58">
Click the +- button on the file icon
<img width="830" alt="Screenshot 2024-06-25 at 11 32 39 AM" src="https://github.com/endless-sky/endless-sky-wiki/assets/73318970/8ba89b19-53cd-413c-ae58-75a64fac1598">
And then, add a single comment, or start a review if you have multiple suggestions

2024-06-29 16:04 UTC, TheGiraffe3 commented
@Zarkonnen can you take another look at this and review/edit it?

2024-06-29 18:38 UTC, Zarkonnen requested changes

2024-06-29 18:38 UTC, Zarkonnen commented on wiki/CreatingSales.md
> +Added in **v0.10.9**, the above example would make any planet with the "Random Sparrows" "shipyard stock" have a 70% chance of selling 2 Sparrows which have deprecated for 105 days.
deprecated -> depreciated

2024-06-29 18:38 UTC, Zarkonnen commented on wiki/CreatingSales.md
> +        discount <%##>
Need to add depreciation to syntax. Also, percentages should be consistently labelled as <%##> or <%>.

2024-06-29 18:38 UTC, Zarkonnen commented on wiki/CreatingSales.md
> +The above example would make any planet with the "Random Ramscoops" "outfitter stock" have a 5% chance of selling 10 ramscoops that have already been used for 10 days, and whose cost has been lowered
Confusing example because 10 days is less than the depreciation "grace period" and hence their price would not have been lowered.

2024-06-30 03:15 UTC, TheGiraffe3 commented on wiki/CreatingSales.md
> +Added in **v0.10.9**, the above example would make any planet with the "Random Sparrows" "shipyard stock" have a 70% chance of selling 2 Sparrows which have deprecated for 105 days.
```suggestion
Added in **v0.10.9**, the above example would make any planet with the "Random Sparrows" "shipyard stock" have a 70% chance of selling 2 Sparrows which have depreciated for 105 days.
```

2024-10-23 08:07 UTC, TheGiraffe3 commented
Closing until the other PR is reopened.

2024-10-23 09:24 UTC, TheGiraffe3 commented
Reopening, because there's a new PR for this.

2025-02-19 02:44 UTC, closed without merging